version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: lumelia-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lumelia
      POSTGRES_PASSWORD: lumelia
      POSTGRES_DB: lumelia
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
